### ISSUE TITLE
[chord] Merge checkPredecessor/Successor and confirmExist functions

### ISSUE THREAD

**Issue by albero94** [bushidocodes/chord-grpc#34] opened 2019-11-05 03:02 UTC
The core funcitonality of these three functions is to check if a node exist. This logic can be written in one functions and have the others use it or maybe they ended up not being necessary and the logic can be implementing by calling confirm_exists( ) (or another name) directly from the parent function.

**Comment by heidiklum** [comment] 2019-11-29 23:59
I failed to notice this issue when I was glancing through on the previous PR.  I tend to think that this is now resolved in PR #83  so propose the issue is closed.  Any objections?

Resolved in #83 ?

**Comment by bushidocodes** [comment] 2019-12-03 01:11
Resolved by #83

**Closed as completed by bushidocodes** 2019-12-03 01:11 UTC
